import type { Metadata } from "next";
import { Inter, Cormorant_Garamond } from "next/font/google";

import { ScrollTop } from "@/shared/ui";

import "@styles/global.scss";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  display: 'swap',
  preload: true,
});

const cormorantGaramondSans = Cormorant_Garamond({
  variable: "--font-garamond-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  display: 'swap',
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={`${interSans.variable} ${cormorantGaramondSans.variable}`}>
      <body>
        <div className="wrapper">{children}</div>

        <ScrollTop />
      </body>
    </html>
  );
}
